apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-example-cfg
  labels:
    app: admission-webhook-example
webhooks:
  - name: mutating-example.com.cn
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      url: "https://host.docker.internal:443/mutate"
#      service:
#        name: admission-webhook-example-svc
#        namespace: default
#        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1Ea3lOREE0TkRJek1Gb1hEVE14TURreU1qQTROREl6TUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHEwClhVSWZIc3g1YmJUclFad1ZoVmNTSk1RSWd1eElOTEtEb2haOVY2VGh4c2l6NEJNcktlZk9SWmhHc3ZobGk0VnYKbGtsYjd4MlBRYnl4a2dRUVUxb09Hc1huY0h0b1FBUkdBaFhIWk5pdFNjR2JrREVnMUdJR1ErbndqZ1E5WXYzSQpiaGVJSjRUQnN6MHowMVR0ODQ3MVpIcFBkMG1EZ1VWNmpjc0RSZ1NIK081SDlYczFmRW9TakFTMVljWVFyczhsClRQSThiY3pSRExQRjJ6VFZVSGFmd2JBZ1NjbmRRTitLWUFPYXkrWUxPNlVFdjJYQmltMDJ3ZmV4VnRnWmdkcW0KOHVpY24yOTdUYmk2aXcwQUR3V0hreDcwU1A1NlZqdUVXQ25wTTlhRUt5VHVLVnlRbC9tUFdNQmdYSUlTNkhsQQpQWlFvQ3N2cTE2T3IzbXZXZ00wQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZLT3F4NDA1KzUyRXF6NmlyZG1JNllCWHBOb0xNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCV0hHMHRTbU12M2daRHhPR2Y1QVJyM0tyZnkwRlpPMVM4YUJXTklCQWdhNnY0QVE3YwpORFM1TWorbXh0akkzZHFtY1E1dWt5QXZiZWxqVUtCdFVrUGV1Sy84eUVjSm5wa0pkSGV1c201eTZqS3FUNVczCjVoQmVJMWZEYVdBb2hmVDdBNWt0ZnlhYlZyUmhxSm5nY1NXM0laUHZ5WlBXenVFMVh6eVhsTWRBT1ZwUmsvc20KZ3g1VkF5NEVQdFo3NGcyek1xZG5GZHNzOWZ1SUg4cHc4SkZOM3NyZldMZjd2bmZpNGFCRjVCaDU1S3BYNnpkWgpHMDBjVUNxWjB4TVRsdDBqUFdzaW4zYkNLOVY1L1I0ckltemxwSGd6Qm5PeGhaL0xIbW9QRHhWdTZQdnRtb3FXClVzM3ZHRkNHcVVUQ1NuUXV6L3h5dXNJYkZXaGhueW9FSWw3MQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","services"]
    namespaceSelector:
      matchLabels:
        admission-webhook-example: enabled

